[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "data_processor"
description = "Data processor"
version = "0.2.0"
requires-python = ">=3.10"

[project.scripts]
lab-logging = "lab_logging.main:main"

[tool.setuptools.packages.find]
where = ["src"]
